
// Generated 04-nov-2024 10:00:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private Integer idTema;
     private String nombreTema;
     private Set libros = new HashSet(0);

    public Tema() {
    }

	
    public Tema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public Tema(String nombreTema, Set libros) {
       this.nombreTema = nombreTema;
       this.libros = libros;
    }
   
    public Integer getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }
    public String getNombreTema() {
        return this.nombreTema;
    }
    
    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


