package empresa;
// Generated 06-nov-2024 9:46:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private byte deptNo;
     private String dmombre;
     private String loc;
     private Set empleadoses = new HashSet(0);

    public Departamentos() {
    }

    public Departamentos(byte deptNo, String dmombre, String loc) {
        this.deptNo = deptNo;
        this.dmombre = dmombre;
        this.loc = loc;
    }
    
    

	
    public Departamentos(byte deptNo) {
        this.deptNo = deptNo;
    }
    public Departamentos(byte deptNo, String dmombre, String loc, Set empleadoses) {
       this.deptNo = deptNo;
       this.dmombre = dmombre;
       this.loc = loc;
       this.empleadoses = empleadoses;
    }
   
    public byte getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(byte deptNo) {
        this.deptNo = deptNo;
    }
    public String getDmombre() {
        return this.dmombre;
    }
    
    public void setDmombre(String dmombre) {
        this.dmombre = dmombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


