
// Generated 04-nov-2024 10:00:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer idLibro;
     private Autor autor;
     private Editorial editorial;
     private Tema tema;
     private String isbn;
     private String titulo;
     private byte numeroEjemplares;
     private Set prestamos = new HashSet(0);

    public Libro() {
    }

	
    public Libro(Autor autor, Editorial editorial, Tema tema, String isbn, String titulo, byte numeroEjemplares) {
        this.autor = autor;
        this.editorial = editorial;
        this.tema = tema;
        this.isbn = isbn;
        this.titulo = titulo;
        this.numeroEjemplares = numeroEjemplares;
    }
    public Libro(Autor autor, Editorial editorial, Tema tema, String isbn, String titulo, byte numeroEjemplares, Set prestamos) {
       this.autor = autor;
       this.editorial = editorial;
       this.tema = tema;
       this.isbn = isbn;
       this.titulo = titulo;
       this.numeroEjemplares = numeroEjemplares;
       this.prestamos = prestamos;
    }
   
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public Editorial getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public byte getNumeroEjemplares() {
        return this.numeroEjemplares;
    }
    
    public void setNumeroEjemplares(byte numeroEjemplares) {
        this.numeroEjemplares = numeroEjemplares;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


