
// Generated 04-nov-2024 10:00:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private Integer idSocio;
     private String nombreCompleto;
     private String direccion;
     private String correo;
     private String telefono;
     private String foto;
     private Set prestamos = new HashSet(0);

    public Socio() {
    }

	
    public Socio(String nombreCompleto, String direccion, String telefono, String foto) {
        this.nombreCompleto = nombreCompleto;
        this.direccion = direccion;
        this.telefono = telefono;
        this.foto = foto;
    }
    public Socio(String nombreCompleto, String direccion, String correo, String telefono, String foto, Set prestamos) {
       this.nombreCompleto = nombreCompleto;
       this.direccion = direccion;
       this.correo = correo;
       this.telefono = telefono;
       this.foto = foto;
       this.prestamos = prestamos;
    }
   
    public Integer getIdSocio() {
        return this.idSocio;
    }
    
    public void setIdSocio(Integer idSocio) {
        this.idSocio = idSocio;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


